model2:
  name: SimpleCNN
  architecture:
    layers:
      - type: Conv2d
        parameter: (3, 16,(3, 3), 1,1)
      - type: BatchNorm2d
        num_features: 16
      - type: ReLU
      - type: MaxPool2d
        parameter: ((2,2), 2)
      - type: Conv2d
        parameter: (16, 64,(3, 3), 1,1)
      - type: BatchNorm2d
        num_features: 64
      - type: ReLU
      - type: MaxPool2d
        parameter: ((2,2), 2)
      - type: Conv2d
        parameter: (64, 128,(3, 3), 1,1)
      - type: BatchNorm2d
        num_features: 128
      - type: ReLU
      - type: MaxPool2d
        parameter: ((2,2), 2)
      - type: Flatten
      - type: Linear
        parameter: (25088, 64)
      - type: Tanh
      - type: Dropout
        p: 0.5
      - type: Linear
        parameter: (64, 64)
      - type: Tanh
      - type: Dropout
        p: 0.5
        parameter: (64, 2)
  loss_function: CrossEntropyLoss
  optimizer:
    type: RMSprop
    learning_rate: 0.0001
    weight_decay: 0.00001